### PR TITLE
Implementing the checkAdd method

### PR DESCRIPTION
**Pull request by samytto**
This code intends to provide a new add method to RoaringBitmap, which will return a boolean after inserting an int, indicating if the inserted int was or wasn't already in the set before insertion. Tests and JMH benchmarks for this method were also implemented. 

Results show that the addCheck method was about 1 milliseconds slower than the precedent one.

Same thing for remove method will fellow.

Greetings!

### CODE REVIEW

**Comment by lemire** [comment]
@samytto 

Thanks for the PR.

Can you please make sure that you only add the lines that need to be added so I can review the proposed changes safely? For example, the current PR modifies unrelated files like ArrayContainer.java. You should only modify what needs to be modified. One needs to examine and understand all changes. Note that according to Travis, the PR breaks the unit tests: ideally, we would prefer not to have such problems.

If you prefer I can do a manual code integration, picking only the relevant functions.

**Comment by lemire** [comment]
@samytto It might easier to withdraw this PR and re-issue a new one starting from a clean fork of the main code.

**Comment by samytto** [comment]
Ok. It is mixed with the changes of an older pull request. I will clean that.

**Comment by lemire** [comment]
@samytto  Excellent. Looking forward to it.

As I said, it might be easier to start anew with a fresh fork and a new PR.

**Comment by lemire** [comment]
I have manually merged the PR : 

https://github.com/lemire/RoaringBitmap/commit/3d24f5785ca8ddd4bc856fa2ac9098b23e5fed4e

To avoid the need for manual mergers in the future, please sync your code with the master branch and only modify what needs to be modified.

**Comment by samytto** [comment]
Ok. Thanks. I have checked, and the new parts have been well merged with the actual code.

Cheers!

**Pull request closed without merging**
